name: Scala CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Install CIRCT
        run: |
          mkdir usr
          wget https://github.com/llvm/circt/releases/download/sifive%2F1%2F15%2F0/circt-bin-ubuntu-20.04.tar.gz -O - | tar -zx -C usr/
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH
      - name: Setup and run tests
        run: sbt test
